import { describe, it, expect } from 'vitest';
import {
  parseTle,
  propagateEcliptic,
  orbitPath,
  eciToEcliptic,
  simDaysToUtcMs,
  TT_MINUS_UT_S,
  OBLIQUITY_J2000_DEG,
  AU_KM,
  type Tle,
} from '../src/sim/sgp4.js';
import fixture from './fixtures/sgp4_iss.json';

// The fixture was generated by the authoritative Python `sgp4` package
// (Braddock Gaskill — its C++ backend passes Vallado's official `tcppver`
// reference). Its `tDays` is days from J2000.0 in UT (a pure JD offset). Our
// wrapper's propagateEcliptic() takes TT (the app's sim clock) and converts to
// UT internally, so we feed it `tDays + TT_MINUS_UT_S/86400` to land on the
// same UT instant the reference used.
const f = fixture as unknown as {
  tle: [string, string];
  epochJd: number;
  vectors: {
    off: number;
    tDays: number;
    eci: { x: number; y: number; z: number };
    geodetic: { lat: number; lon: number; alt: number };
  }[];
};

const tle: Tle = {
  name: 'ISS (ZARYA)',
  noradId: 25544,
  line1: f.tle[0],
  line2: f.tle[1],
};

// satellite.js and the Python reference agree to ~8 m over a full orbit
// (measured in the B1 spike). 10 km is a generous margin that still catches a
// frame/time bug (a 1-day error moves the ISS ~250 000 km; a frame mix-up
// moves it thousands of km).
const ECI_TOL_KM = 10;

describe('sgp4 (satellite.js wrapper)', () => {
  it('parses the ISS TLE without error', () => {
    const s = parseTle(tle);
    expect(s.satrec.error).toBe(0);
    expect(s.tle.noradId).toBe(25544);
  });

  it('throws on a malformed TLE', () => {
    expect(() =>
      parseTle({ name: 'bad', noradId: 1, line1: 'garbage', line2: 'garbage' }),
    ).toThrow();
  });

  it('propagates to the reference ECI position at every sample', () => {
    const s = parseTle(tle);
    for (const v of f.vectors) {
      const tDaysTT = v.tDays + TT_MINUS_UT_S / 86400;
      const out = propagateEcliptic(s, tDaysTT);
      expect(out, `propagation failed at off=${v.off}`).not.toBeNull();
      const [x, y, z] = out!.eci.position;
      const dx = x - v.eci.x;
      const dy = y - v.eci.y;
      const dz = z - v.eci.z;
      const errKm = Math.sqrt(dx * dx + dy * dy + dz * dz);
      expect(errKm, `off=${v.off}: err=${errKm.toFixed(2)} km`).toBeLessThan(ECI_TOL_KM);
    }
  });

  it('keeps the ISS in low Earth orbit (altitude 300–600 km)', () => {
    const s = parseTle(tle);
    for (const v of f.vectors) {
      const out = propagateEcliptic(s, v.tDays + TT_MINUS_UT_S / 86400)!;
      const rKm = Math.hypot(...out.eci.position);
      const altKm = rKm - 6378.137; // WGS72 Earth radius
      expect(altKm).toBeGreaterThan(300);
      expect(altKm).toBeLessThan(600);
    }
  });

  it('converts ECI to ecliptic by a pure rotation (length preserved)', () => {
    const v: [number, number, number] = [1000, 2000, 3000];
    const e = eciToEcliptic(v);
    const lenIn = Math.hypot(...v);
    const lenOut = Math.hypot(...e);
    expect(lenOut).toBeCloseTo(lenIn, 6);
    // x is the shared vernal-equinox axis → unchanged.
    expect(e[0]).toBeCloseTo(v[0], 9);
  });

  it('maps ecliptic position to AU with the right magnitude', () => {
    const s = parseTle(tle);
    const out = propagateEcliptic(s, f.vectors[0].tDays + TT_MINUS_UT_S / 86400)!;
    const rAu = Math.hypot(...out.posAu);
    // ISS radius ~6790 km → ~4.54e-5 AU.
    expect(rAu).toBeGreaterThan(4.0e-5);
    expect(rAu).toBeLessThan(5.0e-5);
    expect(AU_KM).toBe(149_597_870.7);
  });

  it('simDaysToUtcMs subtracts the TT−UT offset', () => {
    // tDays=0 (J2000 in TT) → 69.184 s before J2000 in UT.
    const ms = simDaysToUtcMs(0);
    const j2000Utc = Date.UTC(2000, 0, 1, 12, 0, 0);
    expect(j2000Utc - ms).toBeCloseTo(TT_MINUS_UT_S * 1000, 0);
  });

  it('samples a full orbit path of the requested length', () => {
    const s = parseTle(tle);
    const pts = orbitPath(s, f.vectors[0].tDays + TT_MINUS_UT_S / 86400, 64);
    expect(pts.length).toBe(64);
    // Every point is a valid LEO radius.
    for (const p of pts) {
      const rKm = Math.hypot(...p) * AU_KM;
      expect(rKm).toBeGreaterThan(6600);
      expect(rKm).toBeLessThan(7000);
    }
  });

  it('uses the J2000 obliquity constant', () => {
    expect(OBLIQUITY_J2000_DEG).toBeCloseTo(23.439281, 5);
  });
});
